### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by gcadoret** [Philippe734/VPN-Lifeguard#4]
when i launch the program , i've get this error message
 
![image](https://cloud.githubusercontent.com/assets/125258/23104640/21be1a90-f6d2-11e6-9dad-ab1e0ec06109.png)

Any idea ?

thanks

**Comment by ghost** [comment]
The same error in English:

![2017-04-02 20_46_24-error](https://cloud.githubusercontent.com/assets/14923168/24589608/2a7a1d5c-17e6-11e7-999e-eabca92e105f.png)

Windows 10 64-bit. Version 1.4.14.

**Comment by Philippe734** [comment]
You need to run the app as admin :
http://vpnlifeguard.blogspot.com/p/tuto-rapide.html
