### ISSUE TITLE
New vb.net app released on fork for Windows

### ISSUE THREAD

**Issue by t753** [Philippe734/VPN-Lifeguard#6]
There is a new 2019 VB.Net app for for Windows (7, 8, 10). See it here at this fork:
https://github.com/t753/VPN-Lifeguard/tree/master/Windows/VPN%20Lifeguard%20VB.Net

**Comment by Philippe734** [comment]
I am delighted to discover this portage in VB.Net, bravo and thank you! I will add the link to my main page.
